/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    articles: Article;
    'test-articles': TestArticle;
    categories: Category;
    authors: Author;
    'used-urls': UsedUrl;
    keywords: Keyword;
    'rss-sources': RssSource;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'test-articles': TestArticlesSelect<false> | TestArticlesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    'used-urls': UsedUrlsSelect<false> | UsedUrlsSelect<true>;
    keywords: KeywordsSelect<false> | KeywordsSelect<true>;
    'rss-sources': RssSourcesSelect<false> | RssSourcesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'pipeline-prompt': PipelinePrompt;
    'pipeline-settings': PipelineSetting;
    'pipeline-test-prompt': PipelineTestPrompt;
  };
  globalsSelect: {
    'pipeline-prompt': PipelinePromptSelect<false> | PipelinePromptSelect<true>;
    'pipeline-settings': PipelineSettingsSelect<false> | PipelineSettingsSelect<true>;
    'pipeline-test-prompt': PipelineTestPromptSelect<false> | PipelineTestPromptSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  /**
   * Optional caption displayed below the image on the frontend
   */
  caption?: string | null;
  title?: string | null;
  cloudinaryPublicId?: string | null;
  cloudinaryUrl?: string | null;
  cloudinaryResourceType?: string | null;
  cloudinaryFormat?: string | null;
  cloudinaryVersion?: number | null;
  /**
   * Direct URL to the original file without transformations
   */
  originalUrl?: string | null;
  /**
   * URL with applied transformations
   */
  transformedUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  /**
   * File size in bytes
   */
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  status: 'draft' | 'published';
  category?: (number | null) | Category;
  /**
   * Byline shown on article page
   */
  author?:
    | (
        | 'di-royal-reporter'
        | 'di-entertainment-desk'
        | 'di-music-desk'
        | 'di-film-desk'
        | 'web-desk'
        | 'news-desk'
        | 'celebrity-desk'
        | 'royal-family-desk'
      )
    | null;
  sourceUrls?:
    | {
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  featuredImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Keep under 200 characters — shown in article previews and social sharing.
   */
  excerpt?: string | null;
  embeds?:
    | {
        platform?: string | null;
        embedHtml?: string | null;
        caption?: string | null;
        insertAfterParagraph?: number | null;
        id?: string | null;
      }[]
    | null;
  reviewNote?: string | null;
  /**
   * Pin this article to the top of the homepage
   */
  featured?: boolean | null;
  slug: string;
  featuredImageUrl?: string | null;
  featuredImageAlt?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  publishedDate?: string | null;
  confidence?: number | null;
  headlineVariants?:
    | {
        variant?: string | null;
        id?: string | null;
      }[]
    | null;
  readingTime?: number | null;
  articleType?: ('news' | 'listicle' | 'profile' | 'explainer' | 'timeline' | 'developing') | null;
  /**
   * Lower numbers appear first. Leave blank for default ordering.
   */
  displayOrder?: number | null;
  imageOptions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-articles".
 */
export interface TestArticle {
  id: number;
  title: string;
  status: 'draft' | 'published';
  category?: (number | null) | Category;
  /**
   * Byline shown on article page
   */
  author?:
    | (
        | 'di-royal-reporter'
        | 'di-entertainment-desk'
        | 'di-music-desk'
        | 'di-film-desk'
        | 'web-desk'
        | 'news-desk'
        | 'celebrity-desk'
      )
    | null;
  sourceUrls?:
    | {
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  featuredImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  excerpt?: string | null;
  embeds?:
    | {
        platform?: string | null;
        embedHtml?: string | null;
        caption?: string | null;
        insertAfterParagraph?: number | null;
        id?: string | null;
      }[]
    | null;
  reviewNote?: string | null;
  /**
   * Pin this article to the top of the homepage
   */
  featured?: boolean | null;
  slug: string;
  featuredImageUrl?: string | null;
  featuredImageAlt?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  publishedDate?: string | null;
  confidence?: number | null;
  headlineVariants?:
    | {
        variant?: string | null;
        id?: string | null;
      }[]
    | null;
  readingTime?: number | null;
  articleType?: ('news' | 'listicle' | 'profile' | 'explainer' | 'timeline' | 'developing') | null;
  /**
   * Lower numbers appear first. Leave blank for default ordering.
   */
  displayOrder?: number | null;
  imageOptions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  slug: string;
  role?: string | null;
  bio?: string | null;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "used-urls".
 */
export interface UsedUrl {
  id: number;
  url: string;
  keyword?: string | null;
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "keywords".
 */
export interface Keyword {
  id: number;
  keyword: string;
  category: 'royals' | 'entertainment' | 'celebrity' | 'tv' | 'music' | 'film' | 'lifestyle';
  /**
   * Uncheck to temporarily disable this keyword without deleting it
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rss-sources".
 */
export interface RssSource {
  id: number;
  url: string;
  category?: ('royals' | 'entertainment' | 'celebrity' | 'tv' | 'music' | 'film' | 'lifestyle') | null;
  weight: number;
  /**
   * Uncheck to temporarily disable this source without deleting it
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'test-articles';
        value: number | TestArticle;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'used-urls';
        value: number | UsedUrl;
      } | null)
    | ({
        relationTo: 'keywords';
        value: number | Keyword;
      } | null)
    | ({
        relationTo: 'rss-sources';
        value: number | RssSource;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  title?: T;
  cloudinaryPublicId?: T;
  cloudinaryUrl?: T;
  cloudinaryResourceType?: T;
  cloudinaryFormat?: T;
  cloudinaryVersion?: T;
  originalUrl?: T;
  transformedUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  category?: T;
  author?: T;
  sourceUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  featuredImage?: T;
  body?: T;
  excerpt?: T;
  embeds?:
    | T
    | {
        platform?: T;
        embedHtml?: T;
        caption?: T;
        insertAfterParagraph?: T;
        id?: T;
      };
  reviewNote?: T;
  featured?: T;
  slug?: T;
  featuredImageUrl?: T;
  featuredImageAlt?: T;
  metaTitle?: T;
  metaDescription?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  publishedAt?: T;
  publishedDate?: T;
  confidence?: T;
  headlineVariants?:
    | T
    | {
        variant?: T;
        id?: T;
      };
  readingTime?: T;
  articleType?: T;
  displayOrder?: T;
  imageOptions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "test-articles_select".
 */
export interface TestArticlesSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  category?: T;
  author?: T;
  sourceUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  featuredImage?: T;
  body?: T;
  excerpt?: T;
  embeds?:
    | T
    | {
        platform?: T;
        embedHtml?: T;
        caption?: T;
        insertAfterParagraph?: T;
        id?: T;
      };
  reviewNote?: T;
  featured?: T;
  slug?: T;
  featuredImageUrl?: T;
  featuredImageAlt?: T;
  metaTitle?: T;
  metaDescription?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  publishedAt?: T;
  publishedDate?: T;
  confidence?: T;
  headlineVariants?:
    | T
    | {
        variant?: T;
        id?: T;
      };
  readingTime?: T;
  articleType?: T;
  displayOrder?: T;
  imageOptions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  bio?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "used-urls_select".
 */
export interface UsedUrlsSelect<T extends boolean = true> {
  url?: T;
  keyword?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "keywords_select".
 */
export interface KeywordsSelect<T extends boolean = true> {
  keyword?: T;
  category?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rss-sources_select".
 */
export interface RssSourcesSelect<T extends boolean = true> {
  url?: T;
  category?: T;
  weight?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pipeline-prompt".
 */
export interface PipelinePrompt {
  id: number;
  systemPrompt: string;
  wordCountMin?: number | null;
  wordCountMax?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pipeline-settings".
 */
export interface PipelineSetting {
  id: number;
  /**
   * Turn the entire pipeline on or off
   */
  enabled?: boolean | null;
  schedule?: ('8am' | '8pm' | 'both' | 'off') | null;
  maxUrlsPerKeyword?: number | null;
  minContentThreshold?: number | null;
  dedupExpiryHours?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pipeline-test-prompt".
 */
export interface PipelineTestPrompt {
  id: number;
  systemPrompt?: string | null;
  enabled?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pipeline-prompt_select".
 */
export interface PipelinePromptSelect<T extends boolean = true> {
  systemPrompt?: T;
  wordCountMin?: T;
  wordCountMax?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pipeline-settings_select".
 */
export interface PipelineSettingsSelect<T extends boolean = true> {
  enabled?: T;
  schedule?: T;
  maxUrlsPerKeyword?: T;
  minContentThreshold?: T;
  dedupExpiryHours?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pipeline-test-prompt_select".
 */
export interface PipelineTestPromptSelect<T extends boolean = true> {
  systemPrompt?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}