/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  boolean,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_articles_status = pgEnum('enum_articles_status', ['draft', 'published'])
export const enum_articles_author = pgEnum('enum_articles_author', [
  'di-royal-reporter',
  'di-entertainment-desk',
  'di-music-desk',
  'di-film-desk',
  'web-desk',
  'news-desk',
  'celebrity-desk',
  'royal-family-desk',
])
export const enum_articles_article_type = pgEnum('enum_articles_article_type', [
  'news',
  'listicle',
  'profile',
  'explainer',
  'timeline',
  'developing',
])
export const enum_test_articles_status = pgEnum('enum_test_articles_status', ['draft', 'published'])
export const enum_test_articles_author = pgEnum('enum_test_articles_author', [
  'di-royal-reporter',
  'di-entertainment-desk',
  'di-music-desk',
  'di-film-desk',
  'web-desk',
  'news-desk',
  'celebrity-desk',
])
export const enum_test_articles_article_type = pgEnum('enum_test_articles_article_type', [
  'news',
  'listicle',
  'profile',
  'explainer',
  'timeline',
  'developing',
])
export const enum_keywords_category = pgEnum('enum_keywords_category', [
  'royals',
  'entertainment',
  'celebrity',
  'tv',
  'music',
  'film',
  'lifestyle',
])
export const enum_pipeline_settings_schedule = pgEnum('enum_pipeline_settings_schedule', [
  '8am',
  '8pm',
  'both',
  'off',
])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    cloudinaryPublicId: varchar('cloudinary_public_id'),
    cloudinaryUrl: varchar('cloudinary_url'),
    cloudinaryResourceType: varchar('cloudinary_resource_type'),
    cloudinaryFormat: varchar('cloudinary_format'),
    cloudinaryVersion: numeric('cloudinary_version', { mode: 'number' }),
    originalUrl: varchar('original_url'),
    transformedUrl: varchar('transformed_url'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const articles_source_urls = pgTable(
  'articles_source_urls',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    url: varchar('url'),
  },
  (columns) => [
    index('articles_source_urls_order_idx').on(columns._order),
    index('articles_source_urls_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [articles.id],
      name: 'articles_source_urls_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const articles_embeds = pgTable(
  'articles_embeds',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    platform: varchar('platform'),
    embedHtml: varchar('embed_html'),
    caption: varchar('caption'),
    insertAfterParagraph: numeric('insert_after_paragraph', { mode: 'number' }),
  },
  (columns) => [
    index('articles_embeds_order_idx').on(columns._order),
    index('articles_embeds_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [articles.id],
      name: 'articles_embeds_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const articles_tags = pgTable(
  'articles_tags',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    tag: varchar('tag'),
  },
  (columns) => [
    index('articles_tags_order_idx').on(columns._order),
    index('articles_tags_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [articles.id],
      name: 'articles_tags_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const articles_headline_variants = pgTable(
  'articles_headline_variants',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    variant: varchar('variant'),
  },
  (columns) => [
    index('articles_headline_variants_order_idx').on(columns._order),
    index('articles_headline_variants_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [articles.id],
      name: 'articles_headline_variants_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const articles = pgTable(
  'articles',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    status: enum_articles_status('status').notNull().default('draft'),
    category: integer('category_id').references(() => categories.id, {
      onDelete: 'set null',
    }),
    author: enum_articles_author('author'),
    featuredImage: integer('featured_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    body: jsonb('body'),
    excerpt: varchar('excerpt'),
    reviewNote: varchar('review_note'),
    featured: boolean('featured').default(false),
    slug: varchar('slug').notNull(),
    featuredImageUrl: varchar('featured_image_url'),
    featuredImageAlt: varchar('featured_image_alt'),
    metaTitle: varchar('meta_title'),
    metaDescription: varchar('meta_description'),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    publishedDate: timestamp('published_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    confidence: numeric('confidence', { mode: 'number' }),
    readingTime: numeric('reading_time', { mode: 'number' }),
    articleType: enum_articles_article_type('article_type'),
    displayOrder: numeric('display_order', { mode: 'number' }),
    imageOptions: jsonb('image_options'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('articles_category_idx').on(columns.category),
    index('articles_featured_image_idx').on(columns.featuredImage),
    uniqueIndex('articles_slug_idx').on(columns.slug),
    index('articles_updated_at_idx').on(columns.updatedAt),
    index('articles_created_at_idx').on(columns.createdAt),
  ],
)

export const test_articles_source_urls = pgTable(
  'test_articles_source_urls',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    url: varchar('url'),
  },
  (columns) => [
    index('test_articles_source_urls_order_idx').on(columns._order),
    index('test_articles_source_urls_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [test_articles.id],
      name: 'test_articles_source_urls_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const test_articles_embeds = pgTable(
  'test_articles_embeds',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    platform: varchar('platform'),
    embedHtml: varchar('embed_html'),
    caption: varchar('caption'),
    insertAfterParagraph: numeric('insert_after_paragraph', { mode: 'number' }),
  },
  (columns) => [
    index('test_articles_embeds_order_idx').on(columns._order),
    index('test_articles_embeds_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [test_articles.id],
      name: 'test_articles_embeds_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const test_articles_tags = pgTable(
  'test_articles_tags',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    tag: varchar('tag'),
  },
  (columns) => [
    index('test_articles_tags_order_idx').on(columns._order),
    index('test_articles_tags_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [test_articles.id],
      name: 'test_articles_tags_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const test_articles_headline_variants = pgTable(
  'test_articles_headline_variants',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    variant: varchar('variant'),
  },
  (columns) => [
    index('test_articles_headline_variants_order_idx').on(columns._order),
    index('test_articles_headline_variants_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [test_articles.id],
      name: 'test_articles_headline_variants_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const test_articles = pgTable(
  'test_articles',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    status: enum_test_articles_status('status').notNull().default('draft'),
    category: integer('category_id').references(() => categories.id, {
      onDelete: 'set null',
    }),
    author: enum_test_articles_author('author'),
    featuredImage: integer('featured_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    body: jsonb('body'),
    excerpt: varchar('excerpt'),
    reviewNote: varchar('review_note'),
    featured: boolean('featured').default(false),
    slug: varchar('slug').notNull(),
    featuredImageUrl: varchar('featured_image_url'),
    featuredImageAlt: varchar('featured_image_alt'),
    metaTitle: varchar('meta_title'),
    metaDescription: varchar('meta_description'),
    publishedAt: timestamp('published_at', { mode: 'string', withTimezone: true, precision: 3 }),
    publishedDate: timestamp('published_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    confidence: numeric('confidence', { mode: 'number' }),
    readingTime: numeric('reading_time', { mode: 'number' }),
    articleType: enum_test_articles_article_type('article_type'),
    displayOrder: numeric('display_order', { mode: 'number' }),
    imageOptions: jsonb('image_options'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('test_articles_category_idx').on(columns.category),
    index('test_articles_featured_image_idx').on(columns.featuredImage),
    uniqueIndex('test_articles_slug_idx').on(columns.slug),
    index('test_articles_updated_at_idx').on(columns.updatedAt),
    index('test_articles_created_at_idx').on(columns.createdAt),
  ],
)

export const categories = pgTable(
  'categories',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    description: varchar('description'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('categories_slug_idx').on(columns.slug),
    index('categories_updated_at_idx').on(columns.updatedAt),
    index('categories_created_at_idx').on(columns.createdAt),
  ],
)

export const authors = pgTable(
  'authors',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    role: varchar('role'),
    bio: varchar('bio'),
    avatar: integer('avatar_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('authors_slug_idx').on(columns.slug),
    index('authors_avatar_idx').on(columns.avatar),
    index('authors_updated_at_idx').on(columns.updatedAt),
    index('authors_created_at_idx').on(columns.createdAt),
  ],
)

export const used_urls = pgTable(
  'used_urls',
  {
    id: serial('id').primaryKey(),
    url: varchar('url').notNull(),
    keyword: varchar('keyword'),
    expiresAt: timestamp('expires_at', { mode: 'string', withTimezone: true, precision: 3 }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('used_urls_url_idx').on(columns.url),
    index('used_urls_updated_at_idx').on(columns.updatedAt),
    index('used_urls_created_at_idx').on(columns.createdAt),
  ],
)

export const keywords = pgTable(
  'keywords',
  {
    id: serial('id').primaryKey(),
    keyword: varchar('keyword').notNull(),
    category: enum_keywords_category('category').notNull(),
    active: boolean('active').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('keywords_updated_at_idx').on(columns.updatedAt),
    index('keywords_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    articlesID: integer('articles_id'),
    'test-articlesID': integer('test_articles_id'),
    categoriesID: integer('categories_id'),
    authorsID: integer('authors_id'),
    'used-urlsID': integer('used_urls_id'),
    keywordsID: integer('keywords_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_articles_id_idx').on(columns.articlesID),
    index('payload_locked_documents_rels_test_articles_id_idx').on(columns['test-articlesID']),
    index('payload_locked_documents_rels_categories_id_idx').on(columns.categoriesID),
    index('payload_locked_documents_rels_authors_id_idx').on(columns.authorsID),
    index('payload_locked_documents_rels_used_urls_id_idx').on(columns['used-urlsID']),
    index('payload_locked_documents_rels_keywords_id_idx').on(columns.keywordsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['articlesID']],
      foreignColumns: [articles.id],
      name: 'payload_locked_documents_rels_articles_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['test-articlesID']],
      foreignColumns: [test_articles.id],
      name: 'payload_locked_documents_rels_test_articles_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'payload_locked_documents_rels_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['authorsID']],
      foreignColumns: [authors.id],
      name: 'payload_locked_documents_rels_authors_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['used-urlsID']],
      foreignColumns: [used_urls.id],
      name: 'payload_locked_documents_rels_used_urls_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['keywordsID']],
      foreignColumns: [keywords.id],
      name: 'payload_locked_documents_rels_keywords_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const pipeline_prompt = pgTable('pipeline_prompt', {
  id: serial('id').primaryKey(),
  systemPrompt: varchar('system_prompt')
    .notNull()
    .default(
      'You are a senior entertainment journalist writing for DailyInsight.co.uk, a UK entertainment and Royal Family news website. Your style is The Mirror meets Hello! Magazine — punchy, warm, slightly gossipy, always readable. Write one aggregated article combining the key facts from the sources provided. Use UK spelling. 500-600 words. Include: a compelling headline, opening hook paragraph, 3-4 subheadings with short paragraphs, one blockquote with the most dramatic quote from the sources. Return JSON only: { title, excerpt, body (as HTML with h2, p, blockquote tags), category, reviewNote } where category must be exactly one of: royals, celebrity, tv, music, film, lifestyle, entertainment — and reviewNote is a 2-3 sentence editorial note covering: category accuracy, facts to verify before publishing, sensitive claims, and whether the story is time-sensitive. IMPORTANT: If the source articles cover different unrelated stories, identify the topic that appears in the majority of sources and write only about that topic. Completely ignore any source that covers a different topic to the majority. Do not combine unrelated stories into one article. Do not put descriptive phrases, emotions or adjectives in single quotes as if they were film titles or direct quotes. Only use single quotes for actual direct quotes from real people.',
    ),
  wordCountMin: numeric('word_count_min', { mode: 'number' }).default(500),
  wordCountMax: numeric('word_count_max', { mode: 'number' }).default(600),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const pipeline_settings = pgTable('pipeline_settings', {
  id: serial('id').primaryKey(),
  enabled: boolean('enabled').default(true),
  schedule: enum_pipeline_settings_schedule('schedule').default('8am'),
  maxUrlsPerKeyword: numeric('max_urls_per_keyword', { mode: 'number' }).default(3),
  minContentThreshold: numeric('min_content_threshold', { mode: 'number' }).default(500),
  dedupExpiryHours: numeric('dedup_expiry_hours', { mode: 'number' }).default(24),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const pipeline_test_prompt = pgTable('pipeline_test_prompt', {
  id: serial('id').primaryKey(),
  systemPrompt: varchar('system_prompt'),
  enabled: boolean('enabled').default(false),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_articles_source_urls = relations(articles_source_urls, ({ one }) => ({
  _parentID: one(articles, {
    fields: [articles_source_urls._parentID],
    references: [articles.id],
    relationName: 'sourceUrls',
  }),
}))
export const relations_articles_embeds = relations(articles_embeds, ({ one }) => ({
  _parentID: one(articles, {
    fields: [articles_embeds._parentID],
    references: [articles.id],
    relationName: 'embeds',
  }),
}))
export const relations_articles_tags = relations(articles_tags, ({ one }) => ({
  _parentID: one(articles, {
    fields: [articles_tags._parentID],
    references: [articles.id],
    relationName: 'tags',
  }),
}))
export const relations_articles_headline_variants = relations(
  articles_headline_variants,
  ({ one }) => ({
    _parentID: one(articles, {
      fields: [articles_headline_variants._parentID],
      references: [articles.id],
      relationName: 'headlineVariants',
    }),
  }),
)
export const relations_articles = relations(articles, ({ one, many }) => ({
  category: one(categories, {
    fields: [articles.category],
    references: [categories.id],
    relationName: 'category',
  }),
  sourceUrls: many(articles_source_urls, {
    relationName: 'sourceUrls',
  }),
  featuredImage: one(media, {
    fields: [articles.featuredImage],
    references: [media.id],
    relationName: 'featuredImage',
  }),
  embeds: many(articles_embeds, {
    relationName: 'embeds',
  }),
  tags: many(articles_tags, {
    relationName: 'tags',
  }),
  headlineVariants: many(articles_headline_variants, {
    relationName: 'headlineVariants',
  }),
}))
export const relations_test_articles_source_urls = relations(
  test_articles_source_urls,
  ({ one }) => ({
    _parentID: one(test_articles, {
      fields: [test_articles_source_urls._parentID],
      references: [test_articles.id],
      relationName: 'sourceUrls',
    }),
  }),
)
export const relations_test_articles_embeds = relations(test_articles_embeds, ({ one }) => ({
  _parentID: one(test_articles, {
    fields: [test_articles_embeds._parentID],
    references: [test_articles.id],
    relationName: 'embeds',
  }),
}))
export const relations_test_articles_tags = relations(test_articles_tags, ({ one }) => ({
  _parentID: one(test_articles, {
    fields: [test_articles_tags._parentID],
    references: [test_articles.id],
    relationName: 'tags',
  }),
}))
export const relations_test_articles_headline_variants = relations(
  test_articles_headline_variants,
  ({ one }) => ({
    _parentID: one(test_articles, {
      fields: [test_articles_headline_variants._parentID],
      references: [test_articles.id],
      relationName: 'headlineVariants',
    }),
  }),
)
export const relations_test_articles = relations(test_articles, ({ one, many }) => ({
  category: one(categories, {
    fields: [test_articles.category],
    references: [categories.id],
    relationName: 'category',
  }),
  sourceUrls: many(test_articles_source_urls, {
    relationName: 'sourceUrls',
  }),
  featuredImage: one(media, {
    fields: [test_articles.featuredImage],
    references: [media.id],
    relationName: 'featuredImage',
  }),
  embeds: many(test_articles_embeds, {
    relationName: 'embeds',
  }),
  tags: many(test_articles_tags, {
    relationName: 'tags',
  }),
  headlineVariants: many(test_articles_headline_variants, {
    relationName: 'headlineVariants',
  }),
}))
export const relations_categories = relations(categories, () => ({}))
export const relations_authors = relations(authors, ({ one }) => ({
  avatar: one(media, {
    fields: [authors.avatar],
    references: [media.id],
    relationName: 'avatar',
  }),
}))
export const relations_used_urls = relations(used_urls, () => ({}))
export const relations_keywords = relations(keywords, () => ({}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    articlesID: one(articles, {
      fields: [payload_locked_documents_rels.articlesID],
      references: [articles.id],
      relationName: 'articles',
    }),
    'test-articlesID': one(test_articles, {
      fields: [payload_locked_documents_rels['test-articlesID']],
      references: [test_articles.id],
      relationName: 'test-articles',
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: 'categories',
    }),
    authorsID: one(authors, {
      fields: [payload_locked_documents_rels.authorsID],
      references: [authors.id],
      relationName: 'authors',
    }),
    'used-urlsID': one(used_urls, {
      fields: [payload_locked_documents_rels['used-urlsID']],
      references: [used_urls.id],
      relationName: 'used-urls',
    }),
    keywordsID: one(keywords, {
      fields: [payload_locked_documents_rels.keywordsID],
      references: [keywords.id],
      relationName: 'keywords',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_pipeline_prompt = relations(pipeline_prompt, () => ({}))
export const relations_pipeline_settings = relations(pipeline_settings, () => ({}))
export const relations_pipeline_test_prompt = relations(pipeline_test_prompt, () => ({}))

type DatabaseSchema = {
  enum_articles_status: typeof enum_articles_status
  enum_articles_author: typeof enum_articles_author
  enum_articles_article_type: typeof enum_articles_article_type
  enum_test_articles_status: typeof enum_test_articles_status
  enum_test_articles_author: typeof enum_test_articles_author
  enum_test_articles_article_type: typeof enum_test_articles_article_type
  enum_keywords_category: typeof enum_keywords_category
  enum_pipeline_settings_schedule: typeof enum_pipeline_settings_schedule
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  articles_source_urls: typeof articles_source_urls
  articles_embeds: typeof articles_embeds
  articles_tags: typeof articles_tags
  articles_headline_variants: typeof articles_headline_variants
  articles: typeof articles
  test_articles_source_urls: typeof test_articles_source_urls
  test_articles_embeds: typeof test_articles_embeds
  test_articles_tags: typeof test_articles_tags
  test_articles_headline_variants: typeof test_articles_headline_variants
  test_articles: typeof test_articles
  categories: typeof categories
  authors: typeof authors
  used_urls: typeof used_urls
  keywords: typeof keywords
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  pipeline_prompt: typeof pipeline_prompt
  pipeline_settings: typeof pipeline_settings
  pipeline_test_prompt: typeof pipeline_test_prompt
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_articles_source_urls: typeof relations_articles_source_urls
  relations_articles_embeds: typeof relations_articles_embeds
  relations_articles_tags: typeof relations_articles_tags
  relations_articles_headline_variants: typeof relations_articles_headline_variants
  relations_articles: typeof relations_articles
  relations_test_articles_source_urls: typeof relations_test_articles_source_urls
  relations_test_articles_embeds: typeof relations_test_articles_embeds
  relations_test_articles_tags: typeof relations_test_articles_tags
  relations_test_articles_headline_variants: typeof relations_test_articles_headline_variants
  relations_test_articles: typeof relations_test_articles
  relations_categories: typeof relations_categories
  relations_authors: typeof relations_authors
  relations_used_urls: typeof relations_used_urls
  relations_keywords: typeof relations_keywords
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_pipeline_prompt: typeof relations_pipeline_prompt
  relations_pipeline_settings: typeof relations_pipeline_settings
  relations_pipeline_test_prompt: typeof relations_pipeline_test_prompt
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
